- name: Install nginx on AWS dupa1 dupa2
  hosts: awsdupa
  sudo: True
  tasks:
      - name: install nginx
        yum: name=nginx

      - name: start nginx
        service: name=nginx state=restarted
        

        
  